version: 2.1
executors:
  docker-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project

jobs:
  build-images:
    executor: docker-executor
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: "Build udagram-api-feed"
          command: docker build -t udagram-api-feed ./udagram-api-feed
      - run:
          name: "Build udagram-api-user"
          command: docker build -t udagram-api-user ./udagram-api-user
      - run:
          name: "Build udagram-frontend"
          command: docker build -t udagram-frontend ./udagram-frontend
      - run:
          name: "Build udagram-reverseproxy"
          command: docker build -t reverseproxy ./udagram-reverseproxy
      - run:
          name: "Save Docker images to workspace"
          command: |
            mkdir -p docker-images
            docker save udagram-api-feed -o docker-images/udagram-api-feed.tar
            docker save udagram-api-user -o docker-images/udagram-api-user.tar
            docker save udagram-frontend -o docker-images/udagram-frontend.tar
            docker save reverseproxy -o docker-images/reverseproxy.tar
      - persist_to_workspace:
          root: docker-images
          paths:
            - "udagram-api-feed.tar"
            - "udagram-api-user.tar"
            - "udagram-frontend.tar"
            - "reverseproxy.tar"

  tag-images:
    executor: docker-executor
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: docker-images
      - run:
          name: "Load Docker images from workspace"
          command: |
            docker load -i docker-images/udagram-api-feed.tar
            docker load -i docker-images/udagram-api-user.tar
            docker load -i docker-images/udagram-frontend.tar
            docker load -i docker-images/reverseproxy.tar
      - run:
          name: "Tag udagram-api-feed"
          command: docker tag udagram-api-feed thefinitemonkey/udagram-api-feed:v1
      - run:
          name: "Tag udagram-api-user"
          command: docker tag udagram-api-user thefinitemonkey/udagram-api-user:v1
      - run:
          name: "Tag udagram-frontend"
          command: docker tag udagram-frontend thefinitemonkey/udagram-frontend:v1
      - run:
          name: "Tag reverseproxy"
          command: docker tag reverseproxy thefinitemonkey/reverseproxy:v1
      - run:
          name: "Save tagged Docker images to workspace"
          command: |
            docker save thefinitemonkey/udagram-api-feed:v1 -o docker-images/udagram-api-feed.tar
            docker save thefinitemonkey/udagram-api-user:v1 -o docker-images/udagram-api-user.tar
            docker save thefinitemonkey/udagram-frontend:v1 -o docker-images/udagram-frontend.tar
            docker save thefinitemonkey/reverseproxy:v1 -o docker-images/reverseproxy.tar
      - persist_to_workspace:
          root: docker-images
          paths:
            - "udagram-api-feed.tar"
            - "udagram-api-user.tar"
            - "udagram-frontend.tar"
            - "reverseproxy.tar"

  push-images:
    executor: docker-executor
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: docker-images
      - run:
          name: "List Docker images"
          command: docker images
      - run:
          name: "Load Docker images from workspace"
          command: |
            docker load -i docker-images/udagram-api-feed.tar
            docker load -i docker-images/udagram-api-user.tar
            docker load -i docker-images/udagram-frontend.tar
            docker load -i docker-images/reverseproxy.tar
      - run:
          name: "Push udagram-api-feed"
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push thefinitemonkey/udagram-api-feed:v1
      - run:
          name: "Push udagram-api-user"
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push thefinitemonkey/udagram-api-user:v1
      - run:
          name: "Push udagram-frontend"
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push thefinitemonkey/udagram-frontend:v1
      - run:
          name: "Push reverseproxy"
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push thefinitemonkey/reverseproxy:v1

workflows:
  build-and-deploy:
    jobs:
      - build-images
      - tag-images:
          requires:
            - build-images
      - push-images:
          requires:
            - tag-images