apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    app: udagram-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: udagram-reverseproxy
        image: thefinitemonkey/udagram-reverseproxy:v7 # Replace with your image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
          limits:
            cpu: "500m"
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: udagram-env-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: udagram-env-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: udagram-env-config
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: udagram-env-config
              key: POSTGRES_DB
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: udagram-env-config
              key: AWS_BUCKET
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: udagram-env-config
              key: AWS_REGION
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: udagram-env-config
              key: AWS_PROFILE
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: udagram-env-config
              key: JWT_SECRET
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: udagram-env-config
              key: URL
        - name: FEED_UPSTREAM
          valueFrom:
            configMapKeyRef:
              name: udagram-env-config
              key: FEED_UPSTREAM
        - name: USER_UPSTREAM
          valueFrom:
            configMapKeyRef:
              name: udagram-env-config
              key: USER_UPSTREAM
