apiVersion: v1
kind: Service
metadata:
  name: udagram-api-user
  labels:
    app: udagram-api-user
spec:
  type: ClusterIP # Use LoadBalancer if you want external access
  ports:
  - port: 8100
    targetPort: 8100
    protocol: TCP
  selector:
    app: udagram-api-user