apiVersion: v1
kind: Service
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  type: ClusterIP # Use LoadBalancer if you want external access
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: udagram-api-feed